
server:
  port: 11000

eureka:
  client:
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/

spring:
  application:
    name: rogersGateway
  cloud:
    gateway:
      routes:
        - id: Onboarding
          uri: lb://Onboarding
          predicates:
            - Path=/onboarding/**
        - id: billingService
          uri: lb://billingService
          predicates:
            - Path=/billing/**



